version: '3.8'



services:
  # install:
  #   image: di.prim.dev/kotel:latest
  #   restart: on-failure
  #   command: yarn run start
  #   working_dir: /app
  #   volumes:
  #     - .:/app
  #     - kotel_node_modules:/app/node_modules
  #     - /etc/localtime:/etc/localtime:ro
  switch:
    image: di.prim.dev/kotel:latest
    restart: always
    command: yarn run ${YARN_RUN_CMD:-start}
    working_dir: /app
    volumes:
      - .:/app
      - kotel_node_modules:/app/node_modules
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/gpiomem:/dev/gpiomem:rwm
      - /dev/gpiochip0:/dev/gpiochip0:rwm
    environment:
      - TZ=Europe/Prague
      - PATH=$PATH:/app/bin
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${PORT:-8433}
      - HOST=${HOST:-127.0.0.1}
    ports:
      - ${HOST:-127.0.0.1}:${PUB_PORT:-${PORT:-8433}}:${PORT:-8433}
    hostname: hassio-rf433
    domainname: local.hass.io
    dns_search:
      - local.hass.io
    dns:
      - 172.30.32.3
    networks:
      hassio:
        ipv4_address: 172.30.33.0
        aliases:
          - kotel

volumes:
  kotel_node_modules:
    driver: local
    name: kotel_node_modules

networks:
  hassio:
    external: true
